package movie

var _ = []string{
	"Baazigar",
	"Jodhaa Akbar",
	"Wake Up Sid",
	"Saala Khadoos",
	"Qayamat Se Qayamat Tak",
	"Delhi Belly",
	"Magadheera",
	"Highway",
	"Aankhen",
	"Rockstar",
	"Piku",
	"Socha Na Tha",
	"Dil Se",
	"Devdas",
	"Hum Aapke Hain Koun",
	"Hum Dil De Chuke Sanam",
	"Jolly LLB",
	"Ghilli",
	"Raanjhanaa",
	"Hungama",
	"Rangeela",
	"Khakee",
	"Kaththi",
	"Rocket Singh: Salesman of the Year",
	"Dear Zindagi",
	"Jaane Tu Ya Jaane Na",
	"Madaari",
	"Peepli Live",
	"Dum Laga Ke Haisha",
	"Mankatha",
	"Ghajini",
	"Yuva",
	"Baghban",
	"Badlapur",
	"Thuppakki",
	"Guzaarish",
	"Kaminey",
	"Kabhi Khushi Kabhie Gham",
	"Sivaji",
	"Maine Pyar Kiya",
	"Once Upon a Time in Mumbaai",
	"Life in a Metro",
	"Ghulam",
	"Ishqiya",
	"Khaleja",
	"Golmaal: Fun Unlimited",
	"Jolly LLB",
	"Mardaani",
	"Psycho Raman",
	"Lootera",
	"Parineeta",
	"Pyaar Ka Punchnama",
	"Shaitan",
	"Band Baaja Baaraat",
	"Srimanthudu",
	"Ghajini",
	"Dookudu",
	"Holiday",
	"Shanghai",
	"Tere Bin Laden",
	"Bhool Bhulaiyaa",
	"No One Killed Jessica",
	"Namastey London",
	"Gunda",
	"Nanban",
	"Paa",
	"Ayan",
	"Talaash",
	"Nannaku Prematho",
	"Fanaa",
	"Don",
	"Dedh Ishqiya",
	"Yennai Arindhaal",
	"Gadar Ek Prem Katha",
	"Bajirao Mastani",
	"Wazir",
	"Dasavatharam",
	"Gabbar is Back",
	"Tamasha",
	"Sanam Teri Kasam",
	"Dhobi Ghat",
	"Raajneeti",
	"Kaabil",
	"Luck by Chance",
	"Race Gurram",
	"Koi Mil Gaya",
	"Atharintiki Daaredi",
	"Shootout at Lokhandwala",
	"Dhamaal",
	"Rab Ne Bana Di Jodi",
	"Hum Tum",
	"Sultan",
	"Chaar Sahibzaade",
	"Pokkiri",
	"Tere Naam",
	"Mohabbatein",
	"Dil To Pagal Hai",
	"Pardes",
	"Rustom",
	"Karthik Calling Karthik",
	"Waqt: The Race Against Time",
	"Raju Ban Gaya Gentleman",
	"Business Man",
	"Fashion",
	"Fan",
	"Main Hoon Na",
	"Ishq",
	"Enthiran",
	"Agneepath",
	"Yeh Jawaani Hai Deewani",
	"Yes Boss",
	"Fukrey",
	"Kaho Naa Pyaar Hai",
	"Aashiqui",
	"Raees",
	"Hasee Toh Phasee",
	"Karan Arjun",
	"Mujhse Shaadi Karogi",
	"Sarkar Raj",
}
