package movie

var hollywoodMovies = []string{
	"Beetlejuice",
	"The Cotton Club",
	"The Shawshank Redemption",
	"Crocodile Dundee",
	"Valkyrie",
	"Ratatouille",
	"City of God",
	"Memento",
	"The Intouchables",
	"Stardust",
	"Apocalypto",
	"Taxi Driver",
	"No Country for Old Men",
	"Planet 51",
	"Looper",
	"Corpse Bride",
	"The Third Man",
	"The Beach",
	"Scarface",
	"Sid and Nancy",
	"Black Swan",
	"Inception",
	"The Deer Hunter",
	"Chasing Amy",
	"Django Unchained",
	"The Silence of the Lambs",
	"American Beauty",
	"Snatch",
	"Midnight Express",
	"Pulp Fiction",
	"Lock Stock and Two Smoking Barrels",
	"Lucky Number Slevin",
	"Rear Window",
	"Pan's Labyrinth",
	"Shutter Island",
	"Reservoir Dogs",
	"The Shining",
	"Midnight in Paris",
	"Les Misérables",
	"Moneyball",
	"The Hangover",
	"The Great Beauty",
	"Gran Torino",
	"Mary and Max",
	"Flight",
	"Requiem for a Dream",
	"The Truman Show",
	"The Artist",
	"Forrest Gump",
	"The Hobbit",
	"Vicky Cristina Barcelona",
	"Slumdog Millionaire",
	"Lost in Translation",
	"Match Point",
	"Psycho",
	"North by Northwest",
	"Madagascar",
	"Downfall",
	"Madagascar",
	"God Bless America",
	"The Social Network",
	"The Pianist",
	"Alive",
	"Casablanca",
	"American Gangster",
	"Catch Me If You Can",
	"American History X",
	"Casino",
	"Pirates of the Caribbean",
	"Crash",
	"The Lord of the Rings",
	"Oldboy",
	"Chocolat",
	"Casino Royale",
	"WALL·E",
	"The Wolf of Wall Street",
	"Hellboy",
	"Sunset Boulevard",
	"The Grand Budapest Hotel",
	"Once Upon a Time in America",
	"Oblivion",
	"V for Vendetta",
	"Gattaca",
	"Silver Linings Playbook",
	"Alice in Wonderland",
	"Gandhi",
	"Pacific Rim",
	"Kiss Kiss Bang Bang",
	"The Quiet American",
	"Cloud Atlas",
	"The Impossible",
	"All Quiet on the Western Front",
	"The English Patient",
	"Dallas Buyers Club",
	"Frida",
	"Before Sunrise",
	"The Rum Diary",
	"The Last Samurai",
	"Chinatown",
	"Calvary",
	"Before Sunset",
	"Spirited Away",
	"Indochine",
	"Boyhood",
	"12 Angry Men",
	"The Imitation Game",
	"Interstellar",
	"Big Nothing",
	"Das Boot",
	"Shrek 2",
	"Sin City",
	"Nebraska",
	"Shrek",
	"Original Sin",
	"Shrek Forever After",
	"Before Midnight",
	"Despicable Me",
	"Troy",
	"The Hobbit",
	"The Great Gatsby",
	"Ice Age",
	"The Lord of the Rings",
	"Ex Machina",
	"The Theory of Everything",
	"Shogun",
	"Spotlight",
	"Vertigo",
	"Whiplash",
	"The Lives of Others",
	"Hotel Rwanda",
	"The Martian",
	"To Kill a Mockingbird",
	"The Hateful Eight",
	"A Separation",
	"The Big Short",
}
